language: python
# make it explicit that we favor the new container-based travis workers
sudo: false

env:
  global:
    - PYTHON="python"
matrix:
  include:
    - python: "3.7-dev"
      env: TOXENV="py37"
    - python: "3.6"
      env: TOXENV="py36"

install: $PYTHON -m pip install tox
script: tox
after_success:
  - $PYTHON -m pip install codecov
  - codecov
